### PAIR

**PANDAS**

In [3]:
import pandas as pd
import numpy as np

1 . ¿Qué diferencia hay entre una Serie y un DataFrame?

In [45]:
# Serie: una sola columna.
# DataFrame: varias columnas (conjunto de Series alineadas).

Es el turno de los DataFrames:

2.1 Crea un array de dos dimensiones con 4 filas y 3 columnas.

In [2]:
array1 = np.random.randint(0, 20, size=(4, 3))
print(array1)

[[ 1  1  0]
 [ 6  5  0]
 [ 1  3  7]
 [11 16  7]]


2.2 Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [ ]:
array1.T.tolist()  #transforma cada columna en una lista de valores que después vamos asignar a cada país

[[1, 6, 1, 11], [1, 5, 3, 16], [0, 0, 7, 7]]

In [59]:
columnas = ["España", "Francia", "Italia"]
diccionario1 = dict(zip(columnas, array1.T.tolist()))  #zip(columnas, array1.T.tolist()) - crea pares (nombre_columna, lista_valores) para el diccionario.
diccionario1

{'España': [1, 6, 1, 11], 'Francia': [1, 5, 3, 16], 'Italia': [0, 0, 7, 7]}

In [60]:
df1 = pd.DataFrame(diccionario1)
print(df1)

   España  Francia  Italia
0       1        1       0
1       6        5       0
2       1        3       7
3      11       16       7


2.3 Descarga el archivo "medallas" y carga el DataFrame.

In [4]:
df_medallas = pd.read_csv("file\medallas.csv")
df_medallas.head()


<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\miguel\AppData\Local\Temp\ipykernel_9412\3578020742.py:1: SyntaxWarning: invalid escape sequence '\m'
  df_medallas = pd.read_csv("file\medallas.csv")


Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827
3           4           Irán   179    181     197
4           5     Kazajistán   155    158     224

In [35]:
df_medallas.index

RangeIndex(start=0, stop=10, step=1)

In [36]:
df_medallas.shape

(10, 5)

2.4 Usando el loc extrae todas las columnas de la fila de Tailandia.

In [ ]:
df_medallas.loc[df_medallas["País"] == "Tailandia", :]

Unnamed: 0       País  Oro  Plata  Bronce
6           7  Tailandia  132    175     278

2.5 Usando el loc extrae todas las columnas de China e Irán.

In [17]:
df_medallas.loc[df_medallas["País"] == "China", :]

Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720

In [18]:
df_medallas.loc[df_medallas["País"] == "Irán", :]

Unnamed: 0  País  Oro  Plata  Bronce
3           4  Irán  179    181     197

In [5]:
df_medallas.loc[(df_medallas["País"] == "China" )|(df_medallas["País"] == "Irán")]

Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197

2.6 Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [21]:
df_medallas.loc[df_medallas["País"] == "China", ["Oro", "Plata", "Bronce"]]

Oro  Plata  Bronce
0  1473    994     720

In [22]:
df_medallas.loc[df_medallas["País"] == "Irán", ["Oro", "Plata", "Bronce"]]

Oro  Plata  Bronce
3  179    181     197

In [6]:
df_medallas.loc[(df_medallas["País"] == "China" )|(df_medallas["País"] == "Irán"), ["Oro", "Plata", "Bronce"] ]

Oro  Plata  Bronce
0  1473    994     720
3   179    181     197

2.7 Usando el iloc extrae la información de la India. Devolved todas las columnas.

In [29]:
df_medallas.index[df_medallas["País"] == "India"]

Index([5], dtype='int64')

In [30]:
df_medallas.iloc[5, :]

Unnamed: 0        6
País          India
Oro             154
Plata           202
Bronce          315
Name: 5, dtype: object

In [7]:
df_medallas.iloc[df_medallas.index[df_medallas["País"] == "India"], :]

Unnamed: 0   País  Oro  Plata  Bronce
5           6  India  154    202     315

2.8 Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [32]:
df_medallas.iloc[1::2, :]

Unnamed: 0             País   Oro  Plata  Bronce
1           2            Japón  1032   1037     985
3           4             Irán   179    181     197
5           6            India   154    202     315
7           8        Indonesia   112    131     240
9          10  Corea del Norte    91    120     235

2.9 Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [10]:
df_medallas.iloc[1::2, -3:]

Oro  Plata  Bronce
1  1032   1037     985
3   179    181     197
5   154    202     315
7   112    131     240
9    91    120     235

2.10 Contesta a las siguientes preguntas:

- ¿Qué país consiguió más de 200 medallas de oro?

- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?



In [11]:
df_medallas.loc[(df_medallas.Oro > 200), ["País"]]

País
0          China
1          Japón
2  Corea del Sur

In [43]:
df_medallas.loc[(df_medallas.Oro > 200) & (df_medallas.Plata > 1000), ['País']]

País
1  Japón

In [44]:
df_medallas.loc[(df_medallas.Oro > 200) & (df_medallas.Bronce > 700), ['País']]

País
0          China
1          Japón
2  Corea del Sur

2.11 Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [ ]:
#creamos una nueva columna con asignación directa df_medallas["total"]

df_medallas["total"] = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"]
df_medallas.head()


Unnamed: 0           País   Oro  Plata  Bronce  total
0           1          China  1473    994     720   3187
1           2          Japón  1032   1037     985   3054
2           3  Corea del Sur   745    663     827   2235
3           4           Irán   179    181     197    557
4           5     Kazajistán   155    158     224    537

Momento de trabajar con Series. Contesta a las siguientes preguntas:

3.1 Crea dos listas:

- Una que se llame "valores" que tenga 7 números aleatorios.

- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [13]:
valores = np.random.randint(0, 30, size=7).tolist()
indices = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

print(valores)
print(indices)

[3, 3, 17, 1, 23, 21, 20]
['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']


3.2 A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [14]:
serie1 = pd.Series(data=valores, index=indices)
print(serie1)

Lunes         3
Martes        3
Miércoles    17
Jueves        1
Viernes      23
Sábado       21
Domingo      20
dtype: int64


3.3 A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

In [15]:
valores = [4, 22, 4, 9, 27, 0, 21]
indices = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

diccionario2 = {}

for dia, valor in zip(indices, valores):
    diccionario2[dia] = valor

print(diccionario2)

{'Lunes': 4, 'Martes': 22, 'Miércoles': 4, 'Jueves': 9, 'Viernes': 27, 'Sábado': 0, 'Domingo': 21}


3.4 Crea una Serie con el diccionario creado en el punto anterior.

In [16]:
serie2 = pd.Series(diccionario2)

print(serie2)

Lunes         4
Martes       22
Miércoles     4
Jueves        9
Viernes      27
Sábado        0
Domingo      21
dtype: int64


3.5 ¿Qué forma tiene esta última Serie?

In [17]:
serie2.shape

(7,)

3.6 ¿Qué tipo de datos tiene?

In [18]:
serie2.dtype

dtype('int64')

3.7 ¿Qué tamaño tiene?

In [19]:
serie2.size

7

3.8 ¿Cuáles son los índices de la Serie?

In [20]:
serie2.index

Index(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')

3.9 ¿Y los values?

In [21]:
serie2.values

array([ 4, 22,  4,  9, 27,  0, 21])

3.10 Extrae el valor para el índice "lunes"

In [22]:
serie2["Lunes"]

np.int64(4)

3.11 Extrae el valor para el índice "lunes", "martes" y "miércoles".

In [24]:
serie2["Lunes"] & serie2["Martes"] & serie2["Miércoles"]

np.int64(4)

In [30]:
for i, v in serie2.items():
    if i in ("Lunes", "Martes", "Miércoles"):
        print(i, "->", v)
        print("----------------")

Lunes -> 4
----------------
Martes -> 22
----------------
Miércoles -> 4
----------------


3.12 Extrae el valor para el índice "lunes" y "domingo".

In [31]:
for i, v in serie2.items():
    if i in ("Lunes", "Domingo"):
        print(i, "->", v)
        print("----------------")

Lunes -> 4
----------------
Domingo -> 21
----------------
