Creación y Indexación:

In [1]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [3]:
arr_1 = np.random.randint(10, 100, size= 50)
print(arr_1)
multiplos = arr_1[::5]
print(multiplos)

[39 33 85 89 75 14 55 80 61 92 58 11 62 16 97 76 96 47 25 78 92 77 65 38
 91 70 97 49 59 58 10 44 52 20 53 49 82 93 20 35 26 19 27 77 16 81 57 55
 10 50]
[39 14 58 76 92 70 10 49 26 81]


2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
arr_2 = np.random.randint(1, 21, size= 30)
print(arr_2)
impares =arr_2[1::2]
print(impares)

[ 6 16 13  5  5 12 17 15  9  1 18  3  5 18  9  2  8 17  7 13 17 12  3 16
  9 13 20 13 16 11]
[16  5 12 15  1  3 18  2 17 13 12 16 13 13 11]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [8]:
arr_3 =arr_2 = np.random.uniform(0 , 21, size=(4,6))
print(arr_3)
arr_3 = np.round(arr_3,2)
print(arr_3)
ultima_fila = arr_3[-1,:]
print(ultima_fila)

[[14.02337038 20.69315962  5.72120609 14.18525361  8.6139445  13.0243932 ]
 [ 2.73304636 10.04048337 16.06513777  2.4345724   5.9230371   9.27897786]
 [ 5.2422262   5.43850489 16.23784231 16.19477597 12.62734657 17.81027213]
 [20.13312884  0.86753354  3.96394908  2.35379182  7.73849115 10.0335922 ]]
[[14.02 20.69  5.72 14.19  8.61 13.02]
 [ 2.73 10.04 16.07  2.43  5.92  9.28]
 [ 5.24  5.44 16.24 16.19 12.63 17.81]
 [20.13  0.87  3.96  2.35  7.74 10.03]]
[20.13  0.87  3.96  2.35  7.74 10.03]


Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [10]:
arr_4 = np.random.uniform(0, 2, size=(2,3,5))
print(arr_4)
arr_4 = np.round(arr_4,1)
print(arr_4)

[[[1.27560538 1.62486419 0.48377917 1.02881475 0.727085  ]
  [0.03533744 0.36425798 1.20406067 0.61436468 1.67165286]
  [0.57617447 0.82669562 1.267303   1.09235109 1.53839448]]

 [[1.69155742 1.12133489 0.13894888 0.88596295 0.34105315]
  [0.63425435 0.12699283 0.56983539 1.53016806 0.34494937]
  [1.32471483 0.69021565 0.78028071 1.21727061 0.51240794]]]
[[[1.3 1.6 0.5 1.  0.7]
  [0.  0.4 1.2 0.6 1.7]
  [0.6 0.8 1.3 1.1 1.5]]

 [[1.7 1.1 0.1 0.9 0.3]
  [0.6 0.1 0.6 1.5 0.3]
  [1.3 0.7 0.8 1.2 0.5]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".


Copy
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])

In [11]:
array4 = np.random.uniform(0, 2, size=(2, 3, 5))
array4 = np.round(array4, 1)
# Crear un array vacío del mismo tamaño pero tipo objeto para strings
array_labels = np.empty_like(array4, dtype=object)
# Calcular media, máximo y mínimo del array
media = array4.mean()
maximo = array4.max()
minimo = array4.min()
# Condiciones
array_labels[array4 == media] = "A"
array_labels[array4 > media] = "B"
array_labels[array4 < media] = "C"
array_labels[array4 == maximo] = "D"
array_labels[array4 == minimo] = "E"
print("Array original:\n", array4)
print("\nArray final:\n", array_labels)

Array original:
 [[[0.2 0.3 1.3 1.5 1.9]
  [0.5 1.4 0.7 1.1 1. ]
  [0.8 0.6 0.3 1.2 0.8]]

 [[1.6 0.2 0.2 1.  1.6]
  [1.7 1.  1.1 0.6 0.6]
  [0.6 0.9 1.  1.1 1.2]]]

Array final:
 [[['E' 'C' 'B' 'B' 'D']
  ['C' 'B' 'C' 'B' 'B']
  ['C' 'C' 'C' 'B' 'C']]

 [['B' 'E' 'E' 'B' 'B']
  ['B' 'B' 'B' 'C' 'C']
  ['C' 'C' 'B' 'B' 'B']]]


Si te queda tiempo, puedes hacer los siguientes ejercicios:

1. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

2. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [15]:
arr_5 = np.random.randint(1, 101, size=(2,3, 5))
print(arr_5)
flat = arr_5.flatten()
print(flat)
flat[::3] = 0
print(flat[::3])
arr_5_mod = flat.reshape(arr_5.shape)
print(arr_5_mod)
print("Array original: \n", arr_5)
print("Array modificado (múltiplos de 3 -> 0):\n", arr_5_mod)

[[[50 16 68 88 43]
  [21 73  1 58 34]
  [34 86  5 93 59]]

 [[29 15 84 46 95]
  [59 71 89 40 25]
  [22 48 38 87 72]]]
[50 16 68 88 43 21 73  1 58 34 34 86  5 93 59 29 15 84 46 95 59 71 89 40
 25 22 48 38 87 72]
[0 0 0 0 0 0 0 0 0 0]
[[[ 0 16 68  0 43]
  [21  0  1 58  0]
  [34 86  0 93 59]]

 [[ 0 15 84  0 95]
  [59  0 89 40  0]
  [22 48  0 87 72]]]
Array original: 
 [[[50 16 68 88 43]
  [21 73  1 58 34]
  [34 86  5 93 59]]

 [[29 15 84 46 95]
  [59 71 89 40 25]
  [22 48 38 87 72]]]
Array modificado (múltiplos de 3 -> 0):
 [[[ 0 16 68  0 43]
  [21  0  1 58  0]
  [34 86  0 93 59]]

 [[ 0 15 84  0 95]
  [59  0 89 40  0]
  [22 48  0 87 72]]]


3. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

4. Utiliza el array 3D del ejercicio anterior de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

5. Utiliza el array 3D del ejercicio anterior 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).